#!/bin/bash

case $(uname -s) in
    "Darwin")
        ioreg -c AppleSmartBattery -w0 | \
        grep -o '"[^"]*" = [^ ]*' | \
        sed -e 's/= //g' -e 's/"//g' | \
        sort | \
        while read key value; do
            case $key in
                "MaxCapacity")
                    export maxcap=$value;;
                "CurrentCapacity")
                    export curcap=$value;;
                "ExternalConnected")
                    if [ "$value" = "Yes" ]; then
						EXT="Changing"
					else
						EXT="Dischanging"
                    fi
                ;;
                "FullyCharged")
                    if [ "$value" = "Yes" ]; then
                        echo "Fully Charged";
						exit;
                    fi
                ;;
            esac
            if [[ -n "$maxcap" && -n $curcap ]]; then
                BAT=`echo "100 * $curcap / $maxcap" | bc`
                echo "$EXT ${BAT}%"
                exit
            fi
        done
esac
